// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/Project.tsx";
import * as $1 from "./routes/[name].tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/componets/About.tsx";
import * as $4 from "./routes/componets/Contact.tsx";
import * as $5 from "./routes/componets/NavBar.tsx";
import * as $6 from "./routes/componets/Skills.tsx";
import * as $7 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/Project.tsx": $0,
    "./routes/[name].tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/componets/About.tsx": $3,
    "./routes/componets/Contact.tsx": $4,
    "./routes/componets/NavBar.tsx": $5,
    "./routes/componets/Skills.tsx": $6,
    "./routes/index.tsx": $7,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
